### ISSUE TITLE
Make this a repository template?

### ISSUE THREAD

**Issue by ethanbb** [open-ephys-plugins/OEPlugin#2]
Github just recently added the feature to make repositories "templates" that can be easily copied: https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/. Seems like it would make sense for this and `OECommonLib`.

This differs from forks because you can't fork a repository into the same account or organization as the original, and you can only have one fork per account. On the other hand, you might have several plugins that are independent projects so shouldn't be linked by fork relationships, but are also all based on the same template.

**Comment by open-ephys-plugins** [comment]
Done!
